#!/bin/sh

case "$1" in
	start)
		printf "Starting apache2 server ..."
		chown www-data.www-data /usr/htdocs/ -R
		apachectl -k start
		echo "done."
		;;
	stop)
		printf "Stopping apache2 server ..."
		apachectl -k stop
		echo "done."
		;;
	restart)
		$0 stop
		sleep 3
		$0 start
		;;
	*)
		echo "Usage: /etc/init.d/S96apache {start|stop|restart}"
		;;
esac
